//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P001_QuanLyCuaHang.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHDN
    {
        public int Id { get; set; }
        public string IdHDN { get; set; }
        public Nullable<int> IdHang { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> DonGiaNhap { get; set; }
        public int ThanhTien { get; set; }

        public virtual Hang Hang { get; set; }
        public virtual HoaDonNhap HoaDonNhap { get; set; }
    }
}
